version: "2"

services:

  web:
    build: .
    ports:
      - "7777:8000"
      - "7779:8001"
    volumes:
      - .:/opt/personfinder
      - vendors:/opt/personfinder/app/vendors

    command: docker/gae-run-app.sh

volumes:
  vendors:
